### PR TITLE
Fix DMA ID assigning bug in `summarize.py`.

### PR DESCRIPTION
**Pull request by cooperjaXC**
Fix issue #11 by merging the summary bugfix branch into its feature branch. 

Before merging, these need to be done:
1. Let the daily GTrends pull and summarizing run on the `bugfix/summary` branch for several days to ensure successful runs. Check to make sure DMA IDs match the names in the print statements. 
2. Test print statement in `summarize.py` needs to be removed after successful repeated testing. It exists to help evaluate point # 1. Lines needing to be deleted are here: https://github.com/ccaoa/google-ece-trends/blob/6e1a62644de39d12e5827ccc99f7186c2843d4dd/summarize.py#L293-L295

### CODE REVIEW

**Comment by cooperjaXC** [comment]
9 Aug '23 daily pull yielded the error below. Presumably missed a variable assignment in `pull_data.py`.
```
Starting Google Trends data pull.
Traceback (most recent call last):
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\late2022_datapulls.py", line 326, in <module>
    full_run_gtrends()
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\late2022_datapulls.py", line 219, in full_run_gtrends
    eugene_payload = pull.payload_builder(
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\pull_data.py", line 118, in payload_builder
    in dma.dma_id_dict()
AttributeError: module 'dma' has no attribute 'dma_id_dict'
```

**Comment by cooperjaXC** [comment]
e9206e0 seems to have fixed the failure detailed in https://github.com/ccaoa/google-ece-trends/pull/12#issuecomment-1672049513.

**Comment by cooperjaXC** [comment]
9 Aug '23 Try 2: First successful full run of `datapulls22.bat`. Summarizing print results are below for reference. 

For an initial test (as outlined by point # 1 in the original pull request — https://github.com/ccaoa/google-ece-trends/pull/12#issue-1842118551), `"611": "Rochester MN-Mason City IA-Austin MN"` checks out in the prints below.

```
Summarizing files.
1 / 23 processed:    usa_states_df_20180603-20220910.xlsx
2 / 23 processed:    usa_temporal_df_20180603-20220910.xlsx
    dma_id                                   dma
0      611  Rochester MN-Mason City IA-Austin MN
1      647               Greenwood-Greenville MS
2      652                              Omaha NE
3      512                          Baltimore MD
4      650                      Oklahoma City OK
..     ...                                   ...
205    749                             Laredo TX
206    820                           Portland OR
207    839                          Las Vegas NV
208    753                            Phoenix AZ
209    755                        Great Falls MT

[210 rows x 2 columns]
3 / 23 processed:    usa_dma_df_20180603-20220910.xlsx
4 / 23 processed:    usa_top_qs_20180603-20220910.xlsx
5 / 23 processed:    usa_rising_qs_20180603-20220910.xlsx
  dma_id                                                dma
0    649                                      Evansville IN
1    529                                      Louisville KY
2    515                                      Cincinnati OH
3    541                                       Lexington KY
4    659                                       Nashville TN
5    736                                   Bowling Green KY
6    632  Paducah KY-Cape Girardeau MO-Harrisburg-Mount ...
7    564                           Charleston-Huntington WV
8    557                                       Knoxville TN
9    531                                   Tri-Cities TN-VA
6 / 23 processed:    ky_dma_20180603-20220910.xlsx
7 / 23 processed:    ky_time_20180603-20220910.xlsx
  dma_id                    dma
0    649          Evansville IN
1    529          Louisville KY
2    527        Indianapolis IN
3    515          Cincinnati OH
4    602             Chicago IL
5    509           Ft. Wayne IN
6    581         Terre Haute IN
7    588  South Bend-Elkhart IN
8    582           Lafayette IN
8 / 23 processed:    in_dma_20180603-20220910.xlsx
9 / 23 processed:    in_time_20180603-20220910.xlsx
   dma_id                          dma
0     535                  Columbus OH
1     515                Cincinnati OH
2     510  Cleveland-Akron (Canton) OH
3     547                    Toledo OH
4     542                    Dayton OH
5     509                 Ft. Wayne IN
6     536                Youngstown OH
7     596                Zanesville OH
8     558                      Lima OH
9     564     Charleston-Huntington WV
10    597               Parkersburg WV
11    554  Wheeling WV-Steubenville OH
10 / 23 processed:    oh_dma_20180603-20220910.xlsx
11 / 23 processed:    oh_time_20180603-20220910.xlsx
   dma_id                                       dma
0     661                             San Angelo TX
1     692                   Beaumont-Port Arthur TX
2     641                            San Antonio TX
3     612                             Shreveport LA
4     625                      Waco-Temple-Bryan TX
5     765                                El Paso TX
6     651                                Lubbock TX
7     657                         Sherman TX-Ada OK
8     618                                Houston TX
9     662                     Abilene-Sweetwater TX
10    627              Wichita Falls TX & Lawton OK
11    600                         Corpus Christi TX
12    709   Tyler-Longview(Lufkin & Nacogdoches) TX
13    634                               Amarillo TX
14    623                       Dallas-Ft. Worth TX
15    635                                 Austin TX
16    636  Harlingen-Weslaco-Brownsville-McAllen TX
17    633                         Odessa-Midland TX
18    749                                 Laredo TX
19    626                               Victoria TX
12 / 23 processed:    tx_dma_20210321-20210421.xlsx
13 / 23 processed:    tx_time_20210321-20210421.xlsx
14 / 23 processed:    valentines_states_df_20200214-20210214.xlsx
15 / 23 processed:    valentines_temporal_df_20200214-20210214.xlsx
    dma_id                                   dma
0      611  Rochester MN-Mason City IA-Austin MN
1      647               Greenwood-Greenville MS
2      613               Minneapolis-St. Paul MN
3      626                           Victoria TX
4      673         Columbus-Tupelo-West Point MS
..     ...                                   ...
205    717       Quincy IL-Hannibal MO-Keokuk IA
206    749                             Laredo TX
207    839                          Las Vegas NV
208    820                           Portland OR
209    866                     Fresno-Visalia CA

[210 rows x 2 columns]
16 / 23 processed:    valentines_dma_df_20200214-20210214.xlsx
17 / 23 processed:    valentines_top_qs_20200214-20210214.xlsx
18 / 23 processed:    valentines_rising_qs_20200214-20210214.xlsx
  dma_id                                   dma
0    724                  Fargo-Valley City ND
1    611  Rochester MN-Mason City IA-Austin MN
2    737                            Mankato MN
3    613               Minneapolis-St. Paul MN
4    702               La Crosse-Eau Claire WI
5    676                 Duluth MN-Superior WI
19 / 23 processed:    mn_dma_20200214-20210214.xlsx
20 / 23 processed:    mn_time_20200214-20210214.xlsx
  dma_id                                 dma
0    821                             Bend OR
1    757                            Boise ID
2    801                           Eugene OR
3    813            Medford-Klamath Falls OR
4    820                         Portland OR
5    810  Yakima-Pasco-Richland-Kennewick WA
21 / 23 processed:    or_dma_20200214-20210214.xlsx
22 / 23 processed:    or_time_20200214-20210214.xlsx
23 / 23 processed:    eugene_time_20200214-20210214.xlsx
---------------------------------------------------------------
Run Time: 0 hr, 1 min, 55 sec.
```

**Comment by cooperjaXC** [comment]
10 Aug '23: Another successful full run of `datapulls22.bat`. Print results are below for reference.

`"611": "Rochester MN-Mason City IA-Austin MN"` test detailed in https://github.com/ccaoa/google-ece-trends/pull/12#issuecomment-1672090146 checks out again. In fact, the summary print results below _exactly match_ the one from https://github.com/ccaoa/google-ece-trends/pull/12#issuecomment-1672090146. Great sign.

Next: Test from a machine besides Alex's work machine.

```
Starting Google Trends data pull.

C:\Windows\System32>type "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\log.txt"
Data will be stored in C:\Users\Jacob.Cooper\NACCRRA\Research Team - Documents\Mapping\google_trends\gtrends_data\raw_data .
Will store 23 datasets on 2023-08-10 .
-----------------------------------------------

Storage File                  Data Time Period              Storage Folder
-------------------------     -------------------------     --------------
usa_states_df                 2018-06-03 2022-09-10         ~\google_trends\gtrends_data\raw_data
usa_temporal_df               2018-06-03 2022-09-10         ~\google_trends\gtrends_data\raw_data
usa_dma_df                    2018-06-03 2022-09-10         ~\google_trends\gtrends_data\raw_data
usa_top_qs                    2018-06-03 2022-09-10         ~\google_trends\gtrends_data\raw_data
usa_rising_qs                 2018-06-03 2022-09-10         ~\google_trends\gtrends_data\raw_data
ky_dma                        2018-06-03 2022-09-10         ~\google_trends\gtrends_data\raw_data
ky_time                       2018-06-03 2022-09-10         ~\google_trends\gtrends_data\raw_data
in_dma                        2018-06-03 2022-09-10         ~\google_trends\gtrends_data\raw_data
in_time                       2018-06-03 2022-09-10         ~\google_trends\gtrends_data\raw_data
oh_dma                        2018-06-03 2022-09-10         ~\google_trends\gtrends_data\raw_data
oh_time                       2018-06-03 2022-09-10         ~\google_trends\gtrends_data\raw_data
tx_dma                        2021-03-21 2021-04-21         ~\google_trends\gtrends_data\raw_data
tx_time                       2021-03-21 2021-04-21         ~\google_trends\gtrends_data\raw_data
valentines_states_df          2020-02-14 2021-02-14         ~\google_trends\gtrends_data\raw_data
valentines_temporal_df        2020-02-14 2021-02-14         ~\google_trends\gtrends_data\raw_data
valentines_dma_df             2020-02-14 2021-02-14         ~\google_trends\gtrends_data\raw_data
valentines_top_qs             2020-02-14 2021-02-14         ~\google_trends\gtrends_data\raw_data
valentines_rising_qs          2020-02-14 2021-02-14         ~\google_trends\gtrends_data\raw_data
mn_dma                        2020-02-14 2021-02-14         ~\google_trends\gtrends_data\raw_data
mn_time                       2020-02-14 2021-02-14         ~\google_trends\gtrends_data\raw_data
or_dma                        2020-02-14 2021-02-14         ~\google_trends\gtrends_data\raw_data
or_time                       2020-02-14 2021-02-14         ~\google_trends\gtrends_data\raw_data
eugene_time                   2020-02-14 2021-02-14         ~\google_trends\gtrends_data\raw_data

-----------------------------------------------
 23 out of 23 datasets stored.
-----------------------------------------------

Appending raw files.
1 / 23 processed:    usa_states_df_20180603-20220910_20230810.csv
2 / 23 processed:    usa_temporal_df_20180603-20220910_20230810.csv
3 / 23 processed:    usa_dma_df_20180603-20220910_20230810.csv
4 / 23 processed:    usa_top_qs_20180603-20220910_20230810.csv
5 / 23 processed:    usa_rising_qs_20180603-20220910_20230810.csv
6 / 23 processed:    ky_dma_20180603-20220910_20230810.csv
7 / 23 processed:    ky_time_20180603-20220910_20230810.csv
8 / 23 processed:    in_dma_20180603-20220910_20230810.csv
9 / 23 processed:    in_time_20180603-20220910_20230810.csv
10 / 23 processed:    oh_dma_20180603-20220910_20230810.csv
11 / 23 processed:    oh_time_20180603-20220910_20230810.csv
12 / 23 processed:    tx_dma_20210321-20210421_20230810.csv
13 / 23 processed:    tx_time_20210321-20210421_20230810.csv
14 / 23 processed:    valentines_states_df_20200214-20210214_20230810.csv
15 / 23 processed:    valentines_temporal_df_20200214-20210214_20230810.csv
16 / 23 processed:    valentines_dma_df_20200214-20210214_20230810.csv
17 / 23 processed:    valentines_top_qs_20200214-20210214_20230810.csv
18 / 23 processed:    valentines_rising_qs_20200214-20210214_20230810.csv
19 / 23 processed:    mn_dma_20200214-20210214_20230810.csv
20 / 23 processed:    mn_time_20200214-20210214_20230810.csv
21 / 23 processed:    or_dma_20200214-20210214_20230810.csv
22 / 23 processed:    or_time_20200214-20210214_20230810.csv
23 / 23 processed:    eugene_time_20200214-20210214_20230810.csv
---------------------------------------------------------------


Summarizing files.
1 / 23 processed:    usa_states_df_20180603-20220910.xlsx
2 / 23 processed:    usa_temporal_df_20180603-20220910.xlsx
    dma_id                                   dma
0      611  Rochester MN-Mason City IA-Austin MN
1      647               Greenwood-Greenville MS
2      652                              Omaha NE
3      512                          Baltimore MD
4      650                      Oklahoma City OK
..     ...                                   ...
205    749                             Laredo TX
206    820                           Portland OR
207    839                          Las Vegas NV
208    753                            Phoenix AZ
209    755                        Great Falls MT

[210 rows x 2 columns]
3 / 23 processed:    usa_dma_df_20180603-20220910.xlsx
4 / 23 processed:    usa_top_qs_20180603-20220910.xlsx
5 / 23 processed:    usa_rising_qs_20180603-20220910.xlsx
  dma_id                                                dma
0    649                                      Evansville IN
1    529                                      Louisville KY
2    515                                      Cincinnati OH
3    541                                       Lexington KY
4    659                                       Nashville TN
5    736                                   Bowling Green KY
6    632  Paducah KY-Cape Girardeau MO-Harrisburg-Mount ...
7    564                           Charleston-Huntington WV
8    557                                       Knoxville TN
9    531                                   Tri-Cities TN-VA
6 / 23 processed:    ky_dma_20180603-20220910.xlsx
7 / 23 processed:    ky_time_20180603-20220910.xlsx
  dma_id                    dma
0    649          Evansville IN
1    529          Louisville KY
2    527        Indianapolis IN
3    515          Cincinnati OH
4    602             Chicago IL
5    509           Ft. Wayne IN
6    581         Terre Haute IN
7    588  South Bend-Elkhart IN
8    582           Lafayette IN
8 / 23 processed:    in_dma_20180603-20220910.xlsx
9 / 23 processed:    in_time_20180603-20220910.xlsx
   dma_id                          dma
0     535                  Columbus OH
1     515                Cincinnati OH
2     510  Cleveland-Akron (Canton) OH
3     547                    Toledo OH
4     542                    Dayton OH
5     509                 Ft. Wayne IN
6     536                Youngstown OH
7     596                Zanesville OH
8     558                      Lima OH
9     564     Charleston-Huntington WV
10    597               Parkersburg WV
11    554  Wheeling WV-Steubenville OH
10 / 23 processed:    oh_dma_20180603-20220910.xlsx
11 / 23 processed:    oh_time_20180603-20220910.xlsx
   dma_id                                       dma
0     661                             San Angelo TX
1     692                   Beaumont-Port Arthur TX
2     641                            San Antonio TX
3     612                             Shreveport LA
4     625                      Waco-Temple-Bryan TX
5     765                                El Paso TX
6     651                                Lubbock TX
7     657                         Sherman TX-Ada OK
8     618                                Houston TX
9     662                     Abilene-Sweetwater TX
10    627              Wichita Falls TX & Lawton OK
11    600                         Corpus Christi TX
12    709   Tyler-Longview(Lufkin & Nacogdoches) TX
13    634                               Amarillo TX
14    623                       Dallas-Ft. Worth TX
15    635                                 Austin TX
16    636  Harlingen-Weslaco-Brownsville-McAllen TX
17    633                         Odessa-Midland TX
18    749                                 Laredo TX
19    626                               Victoria TX
12 / 23 processed:    tx_dma_20210321-20210421.xlsx
13 / 23 processed:    tx_time_20210321-20210421.xlsx
14 / 23 processed:    valentines_states_df_20200214-20210214.xlsx
15 / 23 processed:    valentines_temporal_df_20200214-20210214.xlsx
    dma_id                                   dma
0      611  Rochester MN-Mason City IA-Austin MN
1      647               Greenwood-Greenville MS
2      613               Minneapolis-St. Paul MN
3      626                           Victoria TX
4      673         Columbus-Tupelo-West Point MS
..     ...                                   ...
205    717       Quincy IL-Hannibal MO-Keokuk IA
206    749                             Laredo TX
207    839                          Las Vegas NV
208    820                           Portland OR
209    866                     Fresno-Visalia CA

[210 rows x 2 columns]
16 / 23 processed:    valentines_dma_df_20200214-20210214.xlsx
17 / 23 processed:    valentines_top_qs_20200214-20210214.xlsx
18 / 23 processed:    valentines_rising_qs_20200214-20210214.xlsx
  dma_id                                   dma
0    724                  Fargo-Valley City ND
1    611  Rochester MN-Mason City IA-Austin MN
2    737                            Mankato MN
3    613               Minneapolis-St. Paul MN
4    702               La Crosse-Eau Claire WI
5    676                 Duluth MN-Superior WI
19 / 23 processed:    mn_dma_20200214-20210214.xlsx
20 / 23 processed:    mn_time_20200214-20210214.xlsx
  dma_id                                 dma
0    821                             Bend OR
1    757                            Boise ID
2    801                           Eugene OR
3    813            Medford-Klamath Falls OR
4    820                         Portland OR
5    810  Yakima-Pasco-Richland-Kennewick WA
21 / 23 processed:    or_dma_20200214-20210214.xlsx
22 / 23 processed:    or_time_20200214-20210214.xlsx
23 / 23 processed:    eugene_time_20200214-20210214.xlsx
---------------------------------------------------------------
Run Time: 0 hr, 4 min, 20 sec.
```

**Comment by cooperjaXC** [comment]
Alex personal machine run also succeeded on 10 Aug '23. Interesting and encouraging thing is that the test DMA print statements came in a different order than those run on the other machine. The DMAs still match up with their correct DMA_IDs, which means that order of DMAs in any one pull or summary dataset don't matter; the correct values are getting assigned every time. Woo!

This is about ready to merge. 

```
Summarizing files.
1 / 23 processed:    usa_states_df_20180603-20220910.xlsx
2 / 23 processed:    usa_temporal_df_20180603-20220910.xlsx
    dma_id                                       dma
0      724                      Fargo-Valley City ND
1      725                  Sioux Falls(Mitchell) SD
2      722             Lincoln & Hastings-Kearney NE
3      679                        Des Moines-Ames IA
4      698                     Montgomery (Selma) AL
..     ...                                       ...
205    636  Harlingen-Weslaco-Brownsville-McAllen TX
206    566      Harrisburg-Lancaster-Lebanon-York PA
207    569                           Harrisonburg VA
208    533                   Hartford & New Haven CT
209    596                             Zanesville OH

[210 rows x 2 columns]
3 / 23 processed:    usa_dma_df_20180603-20220910.xlsx
4 / 23 processed:    usa_top_qs_20180603-20220910.xlsx
5 / 23 processed:    usa_rising_qs_20180603-20220910.xlsx
  dma_id                                                dma
0    736                                   Bowling Green KY
1    564                           Charleston-Huntington WV
2    515                                      Cincinnati OH
3    649                                      Evansville IN
4    557                                       Knoxville TN
5    541                                       Lexington KY
6    529                                      Louisville KY
7    659                                       Nashville TN
8    632  Paducah KY-Cape Girardeau MO-Harrisburg-Mount ...
9    531                                   Tri-Cities TN-VA
6 / 23 processed:    ky_dma_20180603-20220910.xlsx
7 / 23 processed:    ky_time_20180603-20220910.xlsx
  dma_id                    dma
0    602             Chicago IL
1    515          Cincinnati OH
2    649          Evansville IN
3    509           Ft. Wayne IN
4    527        Indianapolis IN
5    582           Lafayette IN
6    529          Louisville KY
7    588  South Bend-Elkhart IN
8    581         Terre Haute IN
8 / 23 processed:    in_dma_20180603-20220910.xlsx
9 / 23 processed:    in_time_20180603-20220910.xlsx
   dma_id                          dma
0     564     Charleston-Huntington WV
1     515                Cincinnati OH
2     510  Cleveland-Akron (Canton) OH
3     535                  Columbus OH
4     542                    Dayton OH
5     509                 Ft. Wayne IN
6     558                      Lima OH
7     597               Parkersburg WV
8     547                    Toledo OH
9     554  Wheeling WV-Steubenville OH
10    536                Youngstown OH
11    596                Zanesville OH
10 / 23 processed:    oh_dma_20180603-20220910.xlsx
11 / 23 processed:    oh_time_20180603-20220910.xlsx
   dma_id                                       dma
0     661                             San Angelo TX
1     600                         Corpus Christi TX
2     692                   Beaumont-Port Arthur TX
3     625                      Waco-Temple-Bryan TX
4     641                            San Antonio TX
5     662                     Abilene-Sweetwater TX
6     618                                Houston TX
7     612                             Shreveport LA
8     627              Wichita Falls TX & Lawton OK
9     623                       Dallas-Ft. Worth TX
10    651                                Lubbock TX
11    634                               Amarillo TX
12    765                                El Paso TX
13    709   Tyler-Longview(Lufkin & Nacogdoches) TX
14    636  Harlingen-Weslaco-Brownsville-McAllen TX
15    635                                 Austin TX
16    626                               Victoria TX
17    657                         Sherman TX-Ada OK
18    749                                 Laredo TX
19    633                         Odessa-Midland TX
12 / 23 processed:    tx_dma_20210321-20210421.xlsx
13 / 23 processed:    tx_time_20210321-20210421.xlsx
14 / 23 processed:    valentines_states_df_20200214-20210214.xlsx
15 / 23 processed:    valentines_temporal_df_20200214-20210214.xlsx
    dma_id                       dma
0      724      Fargo-Valley City ND
1      647   Greenwood-Greenville MS
2      737                Mankato MN
3      718                Jackson MS
4      725  Sioux Falls(Mitchell) SD
..     ...                       ...
205    535               Columbus OH
206    542                 Dayton OH
207    505                Detroit MI
208    565                 Elmira NY
209    551                Lansing MI

[210 rows x 2 columns]
16 / 23 processed:    valentines_dma_df_20200214-20210214.xlsx
17 / 23 processed:    valentines_top_qs_20200214-20210214.xlsx
18 / 23 processed:    valentines_rising_qs_20200214-20210214.xlsx
  dma_id                                   dma
0    724                  Fargo-Valley City ND
1    737                            Mankato MN
2    613               Minneapolis-St. Paul MN
3    702               La Crosse-Eau Claire WI
4    676                 Duluth MN-Superior WI
5    611  Rochester MN-Mason City IA-Austin MN
19 / 23 processed:    mn_dma_20200214-20210214.xlsx
20 / 23 processed:    mn_time_20200214-20210214.xlsx
  dma_id                                 dma
0    757                            Boise ID
1    820                         Portland OR
2    821                             Bend OR
3    810  Yakima-Pasco-Richland-Kennewick WA
4    813            Medford-Klamath Falls OR
5    801                           Eugene OR
21 / 23 processed:    or_dma_20200214-20210214.xlsx
22 / 23 processed:    or_time_20200214-20210214.xlsx
23 / 23 processed:    eugene_time_20200214-20210214.xlsx
---------------------------------------------------------------
Run Time: 0 hr, 0 min, 41 sec.
```

**Comment by cooperjaXC** [comment]
Test Friday 11 Aug with 2:22 `schtasks` run. If it comes back clean, merge this pull request.

**Review by cooperjaXC — COMMENTED** [review]
Changes reviewed by @cooperjaXC

**Comment by cooperjaXC** [comment]
11 Aug '23 data pull ran as expected. Results had correct DMA IDs in them, and all testing prints are cleared out. Ready to merge #12.
